<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class NguoiDungSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $users = [
            [
                'ten_dang_nhap'     => 'admin',
                'email'             => 'admin@example.com',
                'so_dien_thoai'     => '0901000001',
                'mat_khau_hash'     => Hash::make('Admin@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Quản trị viên hệ thống.',
                'ngay_sinh'         => '1990-01-01',
                'noi_o'             => 'Hà Nội',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'user_test',
                'email'             => 'user@example.com',
                'so_dien_thoai'     => '0901000002',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Tài khoản test thông thường.',
                'ngay_sinh'         => '1995-06-15',
                'noi_o'             => 'Hồ Chí Minh',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'nguoi_dung_private',
                'email'             => 'private@example.com',
                'so_dien_thoai'     => '0901000003',
                'mat_khau_hash'     => Hash::make('Private@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => null,
                'ngay_sinh'         => null,
                'noi_o'             => null,
                'quyen_rieng_tu'    => 'rieng_tu',
                'da_xac_thuc'       => false,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'google_user',
                'email'             => 'oauth@gmail.com',
                'so_dien_thoai'     => null,
                'mat_khau_hash'     => null,
                'anh_dai_dien'      => 'https://lh3.googleusercontent.com/a/default',
                'anh_bia'           => null,
                'tieu_su'           => 'Đăng nhập qua Google.',
                'ngay_sinh'         => null,
                'noi_o'             => 'Đà Nẵng',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> 'google',
                'id_oauth'          => '109876543210987654321',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'inactive_user',
                'email'             => 'inactive@example.com',
                'so_dien_thoai'     => '0901000005',
                'mat_khau_hash'     => Hash::make('Inactive@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Tai khoan da bi vo hieu hoa.',
                'ngay_sinh'         => '1988-03-20',
                'noi_o'             => 'Can Tho',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => false,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'minh_quan',
                'email'             => 'minhquan@example.com',
                'so_dien_thoai'     => '0901000006',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Thich chup anh va phieu luu.',
                'ngay_sinh'         => '1996-04-12',
                'noi_o'             => 'Da Lat',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'thu_thao',
                'email'             => 'thuthao@example.com',
                'so_dien_thoai'     => '0901000007',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Yeu am nhac va viet lach.',
                'ngay_sinh'         => '1998-08-23',
                'noi_o'             => 'Ha Noi',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'hoang_nam',
                'email'             => 'hoangnam@example.com',
                'so_dien_thoai'     => '0901000008',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Dam me lap trinh va phat trien web.',
                'ngay_sinh'         => '1994-11-05',
                'noi_o'             => 'Da Nang',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'lan_anh',
                'email'             => 'lananh@example.com',
                'so_dien_thoai'     => '0901000009',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Thanh vien hoi yeu thich meo.',
                'ngay_sinh'         => '1997-02-14',
                'noi_o'             => 'Sai Gon',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'quoc_bao',
                'email'             => 'quocbao@example.com',
                'so_dien_thoai'     => '0901000010',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Nha thiet ke do hoa tu do.',
                'ngay_sinh'         => '1995-10-30',
                'noi_o'             => 'Nha Trang',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'my_duyen',
                'email'             => 'myduyen@example.com',
                'so_dien_thoai'     => '0901000011',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Thich nau an va lam banh ngot.',
                'ngay_sinh'         => '1999-05-18',
                'noi_o'             => 'Hue',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'tan_phat',
                'email'             => 'tanphat@example.com',
                'so_dien_thoai'     => '0901000012',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Bong ro va du lich bui.',
                'ngay_sinh'         => '1996-07-22',
                'noi_o'             => 'Vung Tau',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'bich_phuong',
                'email'             => 'bichphuong@example.com',
                'so_dien_thoai'     => '0901000013',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Chuyen gia tiep thi ky thuat so.',
                'ngay_sinh'         => '1993-12-09',
                'noi_o'             => 'Hai Phong',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'duc_huy',
                'email'             => 'duchuy@example.com',
                'so_dien_thoai'     => '0901000014',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Thich doc sach va choi co vua.',
                'ngay_sinh'         => '1995-09-17',
                'noi_o'             => 'Ha Noi',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'ngoc_han',
                'email'             => 'ngochan@example.com',
                'so_dien_thoai'     => '0901000015',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Thoi trang va loi song lanh manh.',
                'ngay_sinh'         => '1998-01-25',
                'noi_o'             => 'Sai Gon',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'quang_khai',
                'email'             => 'quangkhai@example.com',
                'so_dien_thoai'     => '0901000016',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Dam me xe may va toc do.',
                'ngay_sinh'         => '1997-03-11',
                'noi_o'             => 'Binh Duong',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'thanh_truc',
                'email'             => 'thanhtruc@example.com',
                'so_dien_thoai'     => '0901000017',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Yeu thien nhien va cay xanh.',
                'ngay_sinh'         => '1996-05-24',
                'noi_o'             => 'Da Lat',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'phuoc_thinh',
                'email'             => 'phuocthinh@example.com',
                'so_dien_thoai'     => '0901000018',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Nguoi thich ca hat va giao luu.',
                'ngay_sinh'         => '1994-06-30',
                'noi_o'             => 'Can Tho',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'diep_anh',
                'email'             => 'diepanh@example.com',
                'so_dien_thoai'     => '0901000019',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Sinh vien thiet ke thoi trang.',
                'ngay_sinh'         => '1999-10-08',
                'noi_o'             => 'Ha Noi',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'ten_dang_nhap'     => 'tien_dat',
                'email'             => 'tiendat@example.com',
                'so_dien_thoai'     => '0901000020',
                'mat_khau_hash'     => Hash::make('User@123'),
                'anh_dai_dien'      => null,
                'anh_bia'           => null,
                'tieu_su'           => 'Huan luyen vien the hinh ca nhan.',
                'ngay_sinh'         => '1995-12-14',
                'noi_o'             => 'Sai Gon',
                'quyen_rieng_tu'    => 'cong_khai',
                'da_xac_thuc'       => true,
                'con_hoat_dong'     => true,
                'nha_cung_cap_oauth'=> null,
                'id_oauth'          => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ];

        // Chỉ insert những user chưa tồn tại
        $existingUsernames = DB::table('nguoi_dung')->pluck('ten_dang_nhap')->toArray();
        $existingEmails = DB::table('nguoi_dung')->whereNotNull('email')->pluck('email')->toArray();
        $existingPhones = DB::table('nguoi_dung')->whereNotNull('so_dien_thoai')->pluck('so_dien_thoai')->toArray();

        $usersToInsert = [];
        foreach ($users as $user) {
            $usernameExists = in_array($user['ten_dang_nhap'], $existingUsernames);
            $emailExists = $user['email'] && in_array($user['email'], $existingEmails);
            $phoneExists = $user['so_dien_thoai'] && in_array($user['so_dien_thoai'], $existingPhones);

            if (!$usernameExists && !$emailExists && !$phoneExists) {
                $usersToInsert[] = $user;
            }
        }

        if (!empty($usersToInsert)) {
            DB::table('nguoi_dung')->insert($usersToInsert);
        }
    }
}